// Mocks generated by Mockito 5.4.0 from annotations
// in nyt/test/features/articles/presentation/cubit/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i10;

import 'package:dartz/dartz.dart' as _i2;
import 'package:location/location.dart' as _i9;
import 'package:location_platform_interface/location_platform_interface.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nyt/core/enum/articles_type.dart' as _i8;
import 'package:nyt/core/error/failures.dart' as _i6;
import 'package:nyt/features/articles/domain/entities/article.dart' as _i7;
import 'package:nyt/features/articles/domain/repositories/article_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocationData_1 extends _i1.SmartFake implements _i3.LocationData {
  _FakeLocationData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ArticleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticleRepository extends _i1.Mock implements _i4.ArticleRepository {
  MockArticleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.Article>>> getMostPopularArticle({
    required _i8.ArticleType? type,
    required int? days,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMostPopularArticle,
          [],
          {
            #type: type,
            #days: days,
          },
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, List<_i7.Article>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.Article>>(
          this,
          Invocation.method(
            #getMostPopularArticle,
            [],
            {
              #type: type,
              #days: days,
            },
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.Article>>>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.Article>>> searchArticle(
          {required String? query}) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchArticle,
          [],
          {#query: query},
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, List<_i7.Article>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.Article>>(
          this,
          Invocation.method(
            #searchArticle,
            [],
            {#query: query},
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.Article>>>);
}

/// A class which mocks [Location].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocation extends _i1.Mock implements _i9.Location {
  MockLocation() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i3.LocationData> get onLocationChanged => (super.noSuchMethod(
        Invocation.getter(#onLocationChanged),
        returnValue: _i5.Stream<_i3.LocationData>.empty(),
      ) as _i5.Stream<_i3.LocationData>);
  @override
  _i5.Future<bool> changeSettings({
    _i3.LocationAccuracy? accuracy = _i3.LocationAccuracy.high,
    int? interval = 1000,
    double? distanceFilter = 0.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeSettings,
          [],
          {
            #accuracy: accuracy,
            #interval: interval,
            #distanceFilter: distanceFilter,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<bool> isBackgroundModeEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isBackgroundModeEnabled,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<bool> enableBackgroundMode({bool? enable = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #enableBackgroundMode,
          [],
          {#enable: enable},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<_i3.LocationData> getLocation() => (super.noSuchMethod(
        Invocation.method(
          #getLocation,
          [],
        ),
        returnValue: _i5.Future<_i3.LocationData>.value(_FakeLocationData_1(
          this,
          Invocation.method(
            #getLocation,
            [],
          ),
        )),
      ) as _i5.Future<_i3.LocationData>);
  @override
  _i5.Future<_i3.PermissionStatus> hasPermission() => (super.noSuchMethod(
        Invocation.method(
          #hasPermission,
          [],
        ),
        returnValue: _i5.Future<_i3.PermissionStatus>.value(
            _i3.PermissionStatus.granted),
      ) as _i5.Future<_i3.PermissionStatus>);
  @override
  _i5.Future<_i3.PermissionStatus> requestPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestPermission,
          [],
        ),
        returnValue: _i5.Future<_i3.PermissionStatus>.value(
            _i3.PermissionStatus.granted),
      ) as _i5.Future<_i3.PermissionStatus>);
  @override
  _i5.Future<bool> serviceEnabled() => (super.noSuchMethod(
        Invocation.method(
          #serviceEnabled,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<bool> requestService() => (super.noSuchMethod(
        Invocation.method(
          #requestService,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  _i5.Future<_i3.AndroidNotificationData?> changeNotificationOptions({
    String? channelName,
    String? title,
    String? iconName,
    String? subtitle,
    String? description,
    _i10.Color? color,
    bool? onTapBringToFront,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeNotificationOptions,
          [],
          {
            #channelName: channelName,
            #title: title,
            #iconName: iconName,
            #subtitle: subtitle,
            #description: description,
            #color: color,
            #onTapBringToFront: onTapBringToFront,
          },
        ),
        returnValue: _i5.Future<_i3.AndroidNotificationData?>.value(),
      ) as _i5.Future<_i3.AndroidNotificationData?>);
}
